******* Ignore this Message, this is a Test

diff --git a/.docker/buildpoc/Dockerfile b/.docker/buildpoc/Dockerfile
--- a/.docker/buildpoc/Dockerfile
+++ b/.docker/buildpoc/Dockerfile
@@ -9,7 +9,7 @@ COPY --chown=everest / ${MYHOME}/FStar/
 RUN rm -rf  ${MYHOME}/FStar/.git
 WORKDIR ${MYHOME}/FStar
 RUN echo $(date -u '+%Y-%m-%d %H:%M:%S') >> ${BUILDLOGFILE}
-RUN make -C src/ocaml-output && make -j ${MAXTHREADS} -C ulib/ml >> ${BUILDLOGFILE} && echo "success" >> "result.txt" || echo "failed" >> "result.txt"
+RUN make -C src/ocaml-output && make -j ${MAXTHREADS} -C ulib/ml >> ${BUILDLOGFILE} && echo "success" > "result.txt" || echo "failed" > "result.txt"
 RUN echo $(date -u '+%Y-%m-%d %H:%M:%S') >> ${BUILDLOGFILE}
 
 
